# Generated by Django 4.2.5 on 2024-03-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_invoice_updated_invoiceitem_updated_order_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suppiler',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
