# Generated by Django 4.2.5 on 2024-03-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_old_cart_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='order',
        ),
    ]
