# Generated by Django 4.2.5 on 2024-03-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_shippingadress_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAdress',
            new_name='ShippingAddress',
        ),
    ]
