# Generated by Django 4.2.5 on 2024-03-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='district',
        ),
    ]
