# Generated by Django 4.2.5 on 2024-03-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppiler',
            name='image',
            field=models.ImageField(blank=True, default='suppiler/defaultlogo.png', null=True, upload_to='suppiler'),
        ),
    ]
